# Generated by Django 4.0.6 on 2022-08-16 03:44

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='imgs_places/default.png', upload_to=places.models.upload_img),
        ),
    ]
