# Generated by Django 4.0.6 on 2022-08-16 04:27

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='default.png', upload_to=places.models.upload_img),
        ),
    ]
